<#
.SYNOPSIS
  One-shot bootstrap for the Splunk AITK + DSDL POC lab (Windows). Mirrors setup.sh.

.DESCRIPTION
  Unlike the BOTS lab, the three Splunk apps this POC needs live on
  Splunkbase BEHIND A LOGIN, so they cannot be auto-downloaded. You stage
  them once in splunk-apps/ (see splunk-apps/README.md), then this script:

    1. Verifies Docker is running.
    2. Discovers the PSC add-on + AITK/MLTK app + DSDL app in splunk-apps/.
    3. Writes docker/.env so Splunk auto-installs them (PSC -> MLTK -> DSDL)
       at first boot via SPLUNK_APPS_URL.
    4. Pre-pulls the DSDL "golden image" container so DSDL doesn't have to
       (it's a few GB; skip with -SkipPull).
    4b. Populates this project's OWN BOTSv1 volume - from bots-data\botsv1\
       if present, else downloads the ~6 GB .tgz there. Self-contained; it
       never reads from Splunk-Environment-Lab. Skip with -SkipBots.
    5. Brings the Splunk container up and waits for it to become healthy.
    6. Prints the exact values to enter on the DSDL Setup page.

.EXAMPLE
  .\setup.ps1
.EXAMPLE
  .\setup.ps1 -SkipPull -SkipBots
.EXAMPLE
  .\setup.ps1 -SkipDownload   # use a .tgz already in bots-data\botsv1\
.EXAMPLE
  .\setup.ps1 -GoldenImage splunk/mltk-container-golden-cpu:5.2.3 -Force
#>
param(
    [string]$Password    = "p@ssw0rd",
    [string]$GoldenImage = "splunk/mltk-container-golden-cpu:5.2.3",
    [string]$UrlV1       = "https://s3.amazonaws.com/botsdataset/botsv1/splunk-pre-indexed/botsv1_data_set.tgz",
    [switch]$SkipPull,
    [switch]$SkipBots,
    [switch]$SkipDownload,
    [switch]$Force
)

$ErrorActionPreference = "Stop"
$RepoRoot    = $PSScriptRoot
$ComposeFile = Join-Path $RepoRoot "docker\docker-compose.yml"
$AppsDir     = Join-Path $RepoRoot "splunk-apps"
$EnvFile     = Join-Path $RepoRoot "docker\.env"
$Container   = "splunk-aitk"
$BotsVolume  = "splunkaitk_splunk-botsv1"
$SplunkUid   = 41812

function Step($m) { Write-Host ""; Write-Host "==> $m" -ForegroundColor Green }
function Info($m) { Write-Host "    $m" }
function Die($m)  { Write-Host "ERROR: $m" -ForegroundColor Red; exit 1 }

# --- 1. Pre-flight ---------------------------------------------------------
Step "Pre-flight checks"
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Die "'docker' not found on PATH. Install Docker Desktop and re-run."
}
docker info *> $null
if ($LASTEXITCODE -ne 0) {
    Die "Docker daemon not reachable. Launch Docker Desktop, wait for the whale icon to settle, then re-run."
}
Info "docker daemon reachable"

# --- 2. Discover the three Splunkbase packages -----------------------------
# Splunkbase filenames are versioned, so match by pattern. PSC is
# platform-specific: for the linux/amd64 Splunk container you MUST stage the
# "Linux 64-bit" build of Python for Scientific Computing.
Step "Locating staged apps in splunk-apps\"
if (-not (Test-Path $AppsDir)) { Die "splunk-apps\ folder is missing. See splunk-apps\README.md." }

function Find-App($label, [string[]]$patterns, [string[]]$exclude) {
    # Splunkbase serves both .tgz and .spl (same gzipped-tar format).
    $matches = Get-ChildItem -Path (Join-Path $AppsDir '*') -Include *.tgz,*.spl -File -ErrorAction SilentlyContinue | Where-Object {
        $name = $_.Name.ToLower()
        $hit  = $false
        foreach ($p in $patterns) { if ($name -like $p) { $hit = $true } }
        foreach ($x in $exclude)  { if ($name -like $x) { $hit = $false } }
        $hit
    }
    if (-not $matches) {
        Die "Could not find the $label package (.tgz/.spl) in splunk-apps\ (looked for: $($patterns -join ', ')). See splunk-apps\README.md."
    }
    if ($matches.Count -gt 1) {
        Info "WARNING: multiple matches for ${label}: $($matches.Name -join ', ') - using the first."
    }
    return ($matches | Select-Object -First 1).Name
}

# PSC: prefer the Linux build; never the Windows/x86 one (won't run in the container).
$psc  = Find-App "Python for Scientific Computing (Linux 64-bit)" @("*scientific-computing*linux*") @("*windows*","*x86*","*64-bit_win*")
$mltk = Find-App "AITK / Machine Learning Toolkit"               @("*machine-learning-toolkit*","*splunk-ai-toolkit*","*ai-toolkit*") @()
$dsdl = Find-App "DSDL (Data Science and Deep Learning)"          @("*deep-learning*","*data-science*") @()

Info "PSC  : $psc"
Info "AITK : $mltk"
Info "DSDL : $dsdl"

# --- 3. Write docker\.env --------------------------------------------------
# Container-side paths: splunk-apps\ is bind-mounted read-only at /tmp/apps.
# Order matters - PSC, then MLTK/AITK, then DSDL.
$appsUrl = "/tmp/apps/$psc,/tmp/apps/$mltk,/tmp/apps/$dsdl"
Step "Writing docker\.env"
@"
# Generated by setup.ps1 - do not commit (gitignored).
SPLUNK_PASSWORD=$Password
SPLUNK_HEC_TOKEN=aitk-hec-token-CHANGE-ME
SPLUNK_APPS_URL=$appsUrl
GOLDEN_IMAGE=$GoldenImage
"@ | Set-Content -Path $EnvFile -Encoding utf8
Info "SPLUNK_APPS_URL=$appsUrl"

# --- 4. Pre-pull the DSDL golden image -------------------------------------
if ($SkipPull) {
    Info "Skipping golden-image pull (-SkipPull). DSDL will pull it on first container start."
} else {
    Step "Pulling DSDL golden image: $GoldenImage (a few GB, one-time)"
    docker pull $GoldenImage
    if ($LASTEXITCODE -ne 0) {
        Info "WARNING: pull failed. You can retry later or let DSDL pull it. Continuing."
    } else {
        Info "golden image present locally"
    }
}

# --- 4b. Populate this project's OWN BOTSv1 volume -------------------------
# Independent of Splunk-Environment-Lab's volume. Source preference:
# Fully self-contained - this project keeps its own copy under
# bots-data\botsv1\ and never reads from Splunk-Environment-Lab. Source order:
#   1. this repo's bots-data\botsv1\         (if already extracted)
#   2. a local .tgz in bots-data\botsv1\     (extracted on the fly)
#   3. download the .tgz (~6 GB, resumable)  (unless -SkipDownload)
function Test-BotsVolume {
    docker volume inspect $BotsVolume *> $null
    if ($LASTEXITCODE -ne 0) { return $false }
    docker run --rm -v "${BotsVolume}:/c" alpine test -d /c/default *> $null
    return ($LASTEXITCODE -eq 0)
}

if ($SkipBots) {
    Info "Skipping BOTSv1 population (-SkipBots)."
} elseif ((Test-BotsVolume) -and (-not $Force)) {
    Step "BOTSv1 volume already populated - skipping (re-run with -Force to repopulate)"
} else {
    Step "Preparing this project's BOTSv1 volume ($BotsVolume)"
    $ownDir = Join-Path $RepoRoot "bots-data\botsv1"
    New-Item -ItemType Directory -Force -Path $ownDir | Out-Null
    $src = $null
    if (Test-Path (Join-Path $ownDir "default")) {
        $src = $ownDir; Info "source: bots-data\botsv1\ (already extracted)"
    } else {
        $tgz = Get-ChildItem -Path $ownDir -Filter *.tgz -File -ErrorAction SilentlyContinue | Select-Object -First 1
        if (-not $tgz) {
            if ($SkipDownload) {
                Die "No BOTSv1 data in $ownDir and -SkipDownload set. Drop botsv1_data_set.tgz there, or drop -SkipDownload."
            }
            $tgzPath = Join-Path $ownDir "botsv1_data_set.tgz"
            Step "Downloading BOTSv1 (~6 GB, resumable) into bots-data\botsv1\"
            Info $UrlV1
            curl.exe -L --fail -C - --progress-bar -o $tgzPath $UrlV1
            if ($LASTEXITCODE -ne 0) { Die "BOTSv1 download failed. Re-run, pass -UrlV1 <url>, or drop the .tgz manually and use -SkipDownload." }
            $tgz = Get-Item $tgzPath
        }
        Step "Validating + extracting $($tgz.Name) into bots-data\botsv1\"
        tar -tzf $tgz.FullName *> $null
        if ($LASTEXITCODE -ne 0) { Die "'$($tgz.FullName)' is not a valid gzipped tar - delete it and re-run." }
        tar -xzf $tgz.FullName -C $ownDir --strip-components 1
        $src = $ownDir
    }

    if ((Test-BotsVolume) -and $Force) {
        Info "wiping volume (-Force)"
        docker compose -f $ComposeFile down *> $null
        docker volume rm $BotsVolume *> $null
    }

    Step "Copying BOTSv1 into $BotsVolume (one-time, a few GB)"
    $shCmd = "set -e; cp -a /src/. /dst/; rm -f /dst/*.tgz; chown -R ${SplunkUid}:${SplunkUid} /dst; du -sh /dst"
    docker run --rm -v "${src}:/src:ro" -v "${BotsVolume}:/dst" alpine sh -c $shCmd
    Info "BOTSv1 volume populated"
}

# --- 5. Bring Splunk up ----------------------------------------------------
Step "Starting Splunk container"
if ($Force) { docker compose -f $ComposeFile up -d --force-recreate }
else        { docker compose -f $ComposeFile up -d }
if ($LASTEXITCODE -ne 0) { Die "docker compose up failed." }

# --- 6. Wait for healthy ---------------------------------------------------
Step "Waiting for Splunk to become healthy (first boot installs 3 apps - up to ~8 min)"
$deadline = (Get-Date).AddMinutes(8)
$last = ""
while ((Get-Date) -lt $deadline) {
    $status = (docker inspect -f '{{.State.Health.Status}}' $Container 2>$null)
    if (-not $status) { $status = "starting" }
    if ($status -eq "healthy") { break }
    if ($status -ne $last) { Info "status: $status"; $last = $status }
    Start-Sleep -Seconds 5
}
if ($status -ne "healthy") {
    Info "WARNING: not healthy yet. Check: docker logs -f $Container"
}

# --- 7. Verify apps + print DSDL setup values ------------------------------
Step "Verifying installed apps"
foreach ($app in @("Splunk_ML_Toolkit","mltk-container","Splunk_SA_Scientific_Python_linux_x86_64")) {
    $code = (docker exec $Container curl -ks -o /dev/null -w '%{http_code}' `
        -u "admin:$Password" "https://localhost:8089/services/apps/local/$app" 2>$null)
    Info "$app : HTTP $code (200 = installed)"
}
if (-not $SkipBots) {
    $bots = (docker exec $Container curl -ks -u "admin:$Password" `
        "https://localhost:8089/services/data/indexes/botsv1?output_mode=json" 2>$null)
    if ($bots -match '"totalEventCount":\s*(\d+)') { Info "botsv1 index : $($Matches[1]) events" }
    else { Info "botsv1 index : not visible yet (give Splunk a minute, then check the UI)" }
}

Write-Host ""
Write-Host "===============================================================" -ForegroundColor Cyan
Write-Host " Splunk AITK + DSDL POC is up." -ForegroundColor Cyan
Write-Host "===============================================================" -ForegroundColor Cyan
Write-Host "  Web UI   : http://localhost:8000"
Write-Host "  Username : admin"
Write-Host "  Password : $Password"
Write-Host ""
Write-Host "Next: open DSDL -> Configuration -> Setup and enter (Docker mode):" -ForegroundColor Yellow
Write-Host "  Container Environment : Docker"
Write-Host "  Docker Host           : tcp://docker-proxy:2375"
Write-Host "  Endpoint URL          : host.docker.internal"
Write-Host "  External URL          : localhost"
Write-Host "  Check Hostname        : Disabled   (under Certificate Settings)"
Write-Host "  (tick the risk checkbox, then click Test & Save)"
Write-Host ""
Write-Host "Then DSDL -> Containers -> start the golden-image container and open JupyterLab." -ForegroundColor Yellow
Write-Host ""
Write-Host "DGA detection POC walkthrough (botsv1 DNS): see dga\README.md" -ForegroundColor Yellow
